-- SMK DIPSA: Mata Pelajaran -> Guru -> Kelas
-- Jalankan di Supabase SQL Editor sebelum memakai dashboard versi ini.

create table if not exists public.subjects (
  id bigint generated by default as identity primary key,
  nama_mapel text not null,
  kelas_id bigint not null references public.classes(id) on delete cascade,
  guru_id uuid not null references public.profiles(id) on delete restrict,
  created_at timestamptz not null default now(),
  constraint subjects_nama_kelas_unique unique (nama_mapel, kelas_id)
);

alter table public.materials add column if not exists mapel_id bigint references public.subjects(id) on delete set null;
alter table public.assignments add column if not exists mapel_id bigint references public.subjects(id) on delete set null;
create index if not exists materials_mapel_id_idx on public.materials(mapel_id);
create index if not exists assignments_mapel_id_idx on public.assignments(mapel_id);
create index if not exists subjects_kelas_id_idx on public.subjects(kelas_id);
create index if not exists subjects_guru_id_idx on public.subjects(guru_id);

-- RLS: kebijakan di bawah mengunci akses berdasarkan guru pemilik mata pelajaran.
alter table public.subjects enable row level security;
alter table public.materials enable row level security;
alter table public.assignments enable row level security;

-- Jika sebelumnya ada policy yang terlalu longgar (mis. authenticated can all), hapus/ubah policy tersebut.
-- Policy ini sengaja diberi nama jelas agar mudah diperiksa.
drop policy if exists subjects_select_policy on public.subjects;
drop policy if exists subjects_admin_insert_policy on public.subjects;
drop policy if exists subjects_admin_update_policy on public.subjects;
drop policy if exists subjects_admin_delete_policy on public.subjects;
drop policy if exists materials_student_teacher_select_policy on public.materials;
drop policy if exists materials_teacher_insert_policy on public.materials;
drop policy if exists materials_teacher_update_policy on public.materials;
drop policy if exists materials_teacher_delete_policy on public.materials;
drop policy if exists assignments_student_teacher_select_policy on public.assignments;
drop policy if exists assignments_teacher_insert_policy on public.assignments;
drop policy if exists assignments_teacher_update_policy on public.assignments;
drop policy if exists assignments_teacher_delete_policy on public.assignments;

create policy subjects_select_policy on public.subjects for select to authenticated
using (
  guru_id = auth.uid()
  or exists (select 1 from public.profiles p where p.id=auth.uid() and p.role='admin')
  or exists (select 1 from public.profiles p where p.id=auth.uid() and p.role='siswa' and p.kelas_id=subjects.kelas_id)
);

create policy subjects_admin_insert_policy on public.subjects for insert to authenticated
with check (exists (select 1 from public.profiles p where p.id=auth.uid() and p.role='admin'));
create policy subjects_admin_update_policy on public.subjects for update to authenticated
using (exists (select 1 from public.profiles p where p.id=auth.uid() and p.role='admin'))
with check (exists (select 1 from public.profiles p where p.id=auth.uid() and p.role='admin'));
create policy subjects_admin_delete_policy on public.subjects for delete to authenticated
using (exists (select 1 from public.profiles p where p.id=auth.uid() and p.role='admin'));

create policy materials_student_teacher_select_policy on public.materials for select to authenticated
using (
  exists (select 1 from public.subjects s join public.profiles p on p.id=auth.uid() where s.id=materials.mapel_id and (s.guru_id=auth.uid() or p.role='admin' or (p.role='siswa' and p.kelas_id=s.kelas_id)))
);
create policy materials_teacher_insert_policy on public.materials for insert to authenticated
with check (exists (select 1 from public.subjects s join public.profiles p on p.id=auth.uid() where s.id=materials.mapel_id and (s.guru_id=auth.uid() or p.role='admin')));
create policy materials_teacher_update_policy on public.materials for update to authenticated
using (exists (select 1 from public.subjects s join public.profiles p on p.id=auth.uid() where s.id=materials.mapel_id and (s.guru_id=auth.uid() or p.role='admin')))
with check (exists (select 1 from public.subjects s join public.profiles p on p.id=auth.uid() where s.id=materials.mapel_id and (s.guru_id=auth.uid() or p.role='admin')));
create policy materials_teacher_delete_policy on public.materials for delete to authenticated
using (exists (select 1 from public.subjects s join public.profiles p on p.id=auth.uid() where s.id=materials.mapel_id and (s.guru_id=auth.uid() or p.role='admin')));

create policy assignments_student_teacher_select_policy on public.assignments for select to authenticated
using (
  exists (select 1 from public.subjects s join public.profiles p on p.id=auth.uid() where s.id=assignments.mapel_id and (s.guru_id=auth.uid() or p.role='admin' or (p.role='siswa' and p.kelas_id=s.kelas_id)))
);
create policy assignments_teacher_insert_policy on public.assignments for insert to authenticated
with check (exists (select 1 from public.subjects s join public.profiles p on p.id=auth.uid() where s.id=assignments.mapel_id and (s.guru_id=auth.uid() or p.role='admin')));
create policy assignments_teacher_update_policy on public.assignments for update to authenticated
using (exists (select 1 from public.subjects s join public.profiles p on p.id=auth.uid() where s.id=assignments.mapel_id and (s.guru_id=auth.uid() or p.role='admin')))
with check (exists (select 1 from public.subjects s join public.profiles p on p.id=auth.uid() where s.id=assignments.mapel_id and (s.guru_id=auth.uid() or p.role='admin')));
create policy assignments_teacher_delete_policy on public.assignments for delete to authenticated
using (exists (select 1 from public.subjects s join public.profiles p on p.id=auth.uid() where s.id=assignments.mapel_id and (s.guru_id=auth.uid() or p.role='admin')));

-- Cek cepat sesudah migrasi:
-- select id,nama_mapel,kelas_id,guru_id from public.subjects order by kelas_id,nama_mapel;
-- select id,judul,mapel_id from public.materials order by created_at desc;
-- select id,judul,mapel_id from public.assignments order by created_at desc;

-- RBAC Kelas: hanya Admin yang boleh menambah, mengubah, atau menghapus kelas.
-- Guru tetap dapat membaca data kelas untuk kebutuhan dashboard, filter siswa,
-- dan pengumpulan tugas.
alter table public.classes enable row level security;

-- Hapus policy lama pada tabel classes agar tidak ada policy permissive
-- yang masih memberikan akses tulis kepada Guru.
do $$
declare
  policy_record record;
begin
  for policy_record in
    select policyname
    from pg_policies
    where schemaname = 'public'
      and tablename = 'classes'
  loop
    execute format('drop policy if exists %I on public.classes', policy_record.policyname);
  end loop;
end $$;

create policy classes_authenticated_select_policy on public.classes
for select to authenticated
using (true);

create policy classes_admin_insert_policy on public.classes
for insert to authenticated
with check (
  exists (select 1 from public.profiles p where p.id = auth.uid() and p.role = 'admin')
);

create policy classes_admin_update_policy on public.classes
for update to authenticated
using (
  exists (select 1 from public.profiles p where p.id = auth.uid() and p.role = 'admin')
)
with check (
  exists (select 1 from public.profiles p where p.id = auth.uid() and p.role = 'admin')
);

create policy classes_admin_delete_policy on public.classes
for delete to authenticated
using (
  exists (select 1 from public.profiles p where p.id = auth.uid() and p.role = 'admin')
);
